### PR TITLE
feat(projects): add more featured projects

### PR DESCRIPTION
**Pull request by chrisvogt**
Since #49 makes the projects searchable, this PR begins to beef up the projects page. It also rewrites project descriptions to be more uniform and concise

Link to current version of this page: https://godaddy.github.io/featured-projects/

### Screenshot

download

### CODE REVIEW

**Comment by beardedeagle** [comment]
Just wondering if it would be good to include the language each project has listed?

**Comment by chrisvogt** [comment]
@beardedeagle yeah, it would be! I'd like to see a separate PR that touches up these cards, adds back the lead maintainer if we're going to keep those around, and maybe adds some [Bootstrap badges](https://getbootstrap.com/docs/4.1/components/badge/) highlighting the tech used or keywords for each project. I can open a GitHub issue for that and mark it as a "good first issue" in case anyone wants to contribute.

If we added an array of tech or tags to each project, then we can easily include that in the on-page search — it already supports an array of strings. I'm thinking something like this, but whomever implements it can decide on the actual structure:

```js
{
  ...currentProjectData,
  tags: ['node.js', 'javascript', 'library', 'CLI']
}
```

**Comment by silasbw** [comment]
FWIW, I'd be OK with removing the lead maintainers.

**Comment by chrisvogt** [comment]
Removed lead maintainers. One last screenshot before merging...

07fe4f9

**Pull request merged**
