### PR TITLE
Feb 2019 security updates

### PR DESCRIPTION
**Pull request by tarkatronic**
The list of packages updated comes from here: https://github.com/godaddy/godaddy.github.io/network/alerts

Additionally, I don't know if this is a major concern, but this may need to be looked at in the future:
```
Post-install message from sass:

Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```

### CODE REVIEW

**Comment by chrisvogt** [comment]
I wonder if anyone would 👎adding [Renovate](https://renovatebot.com/) to this project.

**Comment by ealun** [comment]
Could you open an issue for the Ruby Sass warning?

**Comment by tarkatronic** [comment]
@chrisvogt I've actually got a personal todo to compare renovate/greenkeeper/dependabot/etc to make a recommendation for all repos under our org. That said, I think using *any* of them is a plus, and I'm pretty sure is now written up as an official recommendation in the brand new repository standards. :+1: 

@ealun #108 :smile:

**Comment by ealun** [comment]
:100: ty!

**Pull request merged**
